### ISSUE TITLE
rinvex flags

### ISSUE THREAD

**Issue by ered15** [Tigrov/yii2-country#2]
Hi, can you show an example of how to call a flag with a country code?

**Comment by Tigrov** [comment]
Hi, try this
```php
$us = Country::create('US');
$us->rinvex->getFlag()
```

**Comment by ered15** [comment]
I get:
`use tigrov\country\Country;`

The table does not exist: country

**Comment by Tigrov** [comment]
It requires to apply migrations
```
yii migrate
```
run the command in console

**Comment by ered15** [comment]
I installed /rinvex/country and than used this code: `tigrov\country\Country('US')->getFlag();` seems to be working fine, is it okay to use it like that?

**Comment by Tigrov** [comment]
Yes, that's fine.

**Comment by Tigrov** [comment]
It seems you try to use `rinvex\country\Country('US')->getFlag();`?

**Comment by ered15** [comment]
Yes that's right, is it ok?

**Comment by Tigrov** [comment]
Yes, you can use Rinvex extension directly.
