### ISSUE TITLE
Migration failed with Error while sending QUERY packet

### ISSUE THREAD

**Issue by alladas** [Tigrov/yii2-country#3]
Hello,
Your extension failed while trying to migrate.
This is not the same issue as previous.
My install: Yii 2.0.15.1 Advanced / PHP 7.2.9 / mysql Ver 15.1 Distrib 10.0.35-MariaDB / Linux
Please see below the errors log.

`#0 vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `Sa...')
#1 vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('INSERT INTO `Sa...')
#2 vendor/yiisoft/yii2/db/Migration.php(246): yii\db\Command->execute()
#3 vendor/tigrov/yii2-country/src/migrations/m170405_112954_init.php(106): yii\db\Migration->batchInsert('{{%division_tra...', Array, Array)
#4 vendor/tigrov/yii2-country/src/migrations/m170405_112954_init.php(42): tigrov\country\migrations\m170405_112954_init->loadFromCsv('{{%division_tra...', Array, '/srv/www/htdocs...')
#5 vendor/yiisoft/yii2/db/Migration.php(114): tigrov\country\migrations\m170405_112954_init->safeUp()
#6 vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(725): yii\db\Migration->up()
#7 vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(199): yii\console\controllers\BaseMigrateController->migrateUp('tigrov\\country\\...')
#8 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#9 vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#12 vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#13 vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate', Array)
#14 vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate', Array)
#15 vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#16 console/yii(26): yii\base\Application->run()
#17 {main}
PHP Warning 'yii\base\ErrorException' with message 'Error while sending QUERY packet. PID=23351'

in vendor/yiisoft/yii2/db/Transaction.php:186

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'Error while sen...', '/srv/www/htdocs...', 186, Array)
#1 vendor/yiisoft/yii2/db/Transaction.php(186): PDO->rollBack()
#2 vendor/yiisoft/yii2/db/Migration.php(121): yii\db\Transaction->rollBack()
#3 vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(725): yii\db\Migration->up()
#4 vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(199): yii\console\controllers\BaseMigrateController->migrateUp('tigrov\\country\\...')
#5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#6 vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#8 vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#9 vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#10 vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate', Array)
#11 vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate', Array)
#12 vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#13 console/yii(26): yii\base\Application->run()
#14 {main}`

**Comment by Tigrov** [comment]
Hi,

Could you also send me logs from console?

**Comment by alladas** [comment]
Hi @Tigrov 
The errors message that I pasted are already from console.
Please let me know if you need any other info.
Thanks.

**Comment by alladas** [comment]
The error occurred [at line #106](https://github.com/Tigrov/yii2-country/blob/master/src/migrations/m170405_112954_init.php#L106) initialized [at line #42](https://github.com/Tigrov/yii2-country/blob/master/src/migrations/m170405_112954_init.php#L42) while loading data to division_translation table.

**Comment by alladas** [comment]
Hello again @Tigrov 
Here's what I noticed:
While loading division_translation.csv, it failed at row #10000
Changing "INSERT_ROWS" to 200000 it failed at the last position.
This leads to [line #103](https://github.com/Tigrov/yii2-country/blob/master/src/migrations/m170405_112954_init.php#L103) as the point to check.

**Comment by alladas** [comment]
I felt it is a packet size causing troubles.
Limiting "INSERT_ROWS" to 20000, division_translation.csv get loaded. :-)
But city.csv will not load.
Finally, with "INSERT_ROWS" to 10000, ALL PASSED.
So leaving it at 10000.
Thanks to you.

**Comment by Tigrov** [comment]
Ok, done.
I set it to 10000.

**Comment by alladas** [comment]
Wow, you are fast.
Great. Let's close this.
