### ISSUE TITLE
Call to a member function get() on null

### ISSUE THREAD

**Issue by ered15** [Tigrov/yii2-country#8]
Hi, im try to migrate from a shared environment to a VPS, my hosting provider made a mirror copy to new server but when I run Yii2 admin I get this error:

Any idea what I can do to fix this?

`Call to a member function get() on null`

`in /home/greengo/***/vendor/tigrov/intldata/src/Region.php`

`* @param string $code UN region code, UN sub-region code, ISO 3166-1 alpha-2 country code
     * @return string region name, subregion name, country name
     */
    public static function name($code)
    {
        static $data;
 
        if ($data === null) {
            $data = \ResourceBundle::create(\Locale::getDefault(), 'ICUDATA-region')->get('Countries');
        }
 
        return $data->get((string)$code);
    }`

**Comment by Tigrov** [comment]
Hi, check if intl extension is loaded in PHP.
Also check if locales you use are installed on the server.

**Comment by ered15** [comment]
Hey @tigrov thanks for your answer I've been talking to the hositing support since the new server is a VPS server  it uses CentOS meanwhile the actual server uses cloud Linux, I went ahead and looked at the YII2 requirements.php in both servers and I requested them to match the same requirements of the actual server on the VPS server after a while they answered and said all requirements where added except the ICU library since it's CentOS they say they can't update to version 57 as used in actual server, I was wondering if not having the last ICU as required from yii2 will affect the plug-in since I keep getting the same error and everything works fine on actual server and in local server? https://i.imgur.com/8yyf2oo.png

**Comment by Tigrov** [comment]
Hi,
Yes, it can be the reason, you can see in the code it uses ICU library `\ResourceBundle::create(\Locale::getDefault(), 'ICUDATA-region')`

**Comment by ered15** [comment]
@Tigrov thanks for your fast answer, and YES seems that is the problem, I tried and downloaded the version of ICU on my local environment and got the same error, seems ResourceBundle depends on a higher version for it to work, and also that's why YII2 requirements asks for minimum version 49. thanks for your help well let my hosting provider know this.

**Comment by Tigrov** [comment]
Ok, please report the results after upgrade if they can. I'm also interesting.

**Comment by ered15** [comment]
@Tigrov hosting support tells me they can't seem to upgrade the ICU version on CentOS, the solution they are offering me is to purchase a CloudLinux license for this to work in my VPS, but as you know VPS service is not cheap and in top of that to pay for a CloudLinux license it's just not worth the money, I think I will be staying with my current shared plan that's based in CloudLinux and meets the minimum requirement of YII2 **49.1** or higher* so yeah that's it.

**Comment by Tigrov** [comment]
Ok,
I close the issue.
